alias ydev="yarn dev"
alias ysdev="yarn run start:dev"
alias ylint="yarn run lint"
alias nsdev="npm run start:dev"
alias nstr="npm start"
alias ndev="npm run dev"
alias ntsc="npm run tsc"
alias nlint="npm run lint"
alias kb="microk8s.kubectl"

alias vim="nvim"
