alias update_system="sudo pacman -Syu && yay -Syu && sudo flatpak update && sudo snap refresh"
alias notes="cd ~/Nextcloud/Personal/Notes && nvim"
alias nt="notes"
alias rn="ranger"
alias zshf="source ~/.zshrc"
