#!/bin/zsh
setopt extendedglob
WALLPAPER_PATH="$HOME/.wallpapers"

theme="$(ls "$WALLPAPER_PATH"/*.* | fzf --prompt "Select a Wallpaper: ")"

ln -sfn $theme "$WALLPAPER_PATH/selected"

feh --bg-fill $WALLPAPER_PATH/selected
